<script lang="ts">
  import { onDestroy } from 'svelte';
  import { issuesStore } from '$lib/stores/issues';
  import { generateReportHTML, downloadReportHTML } from '$lib/utils/generate-report';
  import { t } from '$lib/config/app-config';

  let { onClose }: { onClose: () => void } = $props();

  let issues: import('$lib/types').Issue[] = $state([]);
  let criteria: import('$lib/types').QACriterion[] = $state([]);
  let previewHTML = $state('');

  const unsubIssues = issuesStore.issues.subscribe((v) => {
    issues = v;
    updatePreview();
  });
  const unsubCriteria = issuesStore.criteria.subscribe((v) => {
    criteria = v;
    updatePreview();
  });

  function updatePreview() {
    previewHTML = generateReportHTML({ issues, criteria, generatedAt: new Date().toISOString() });
  }

  function handleDownload() {
    downloadReportHTML(previewHTML);
    onClose();
  }

  onDestroy(() => {
    unsubIssues();
    unsubCriteria();
  });
</script>

<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
  <div class="mx-4 w-full max-w-5xl rounded-xl bg-white shadow-2xl max-h-[90vh] flex flex-col">
    <!-- Header -->
    <div class="flex items-center justify-between border-b border-gray-200 p-4">
      <h2 class="text-lg font-semibold text-gray-900">Report Preview</h2>
      <button
        class="rounded p-2 hover:bg-gray-100"
        onclick={onClose}
        aria-label="Close report preview"
      >
        <svg class="h-5 w-5 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>

    <!-- Preview content -->
    <div class="flex-1 overflow-y-auto">
      <div class="flex justify-center">
        <iframe
          class="w-full border-0"
          style="height: 70vh;"
          srcdoc={previewHTML}
          sandbox=""
          title="Report Preview"
        ></iframe>
      </div>
    </div>

    <!-- Footer actions -->
    <div class="border-t border-gray-200 p-4 flex items-center justify-between">
      <div class="text-sm text-gray-500">
        Generated by Structured AI Blueprint QA
      </div>
      <div class="flex gap-3">
        <button
          class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
          onclick={onClose}
        >
          Cancel
        </button>
        <button
          class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 transition-colors"
          onclick={handleDownload}
        >
          Download Report
        </button>
      </div>
    </div>
  </div>
</div>
